const $=id=>document.getElementById(id),E={setupView:$('setupView'),timerView:$('timerView'),summaryView:$('summaryView'),historyView:$('historyView'),walkMinutes:$('walkMinutes'),walkSeconds:$('walkSeconds'),runMinutes:$('runMinutes'),runSeconds:$('runSeconds'),gpsToggle:$('gpsToggle'),weightKg:$('weightKg'),savePresetBtn:$('savePresetBtn'),loadPresetBtn:$('loadPresetBtn'),startBtn:$('startBtn'),soundBtn:$('soundBtn'),historyBtn:$('historyBtn'),closeHistoryBtn:$('closeHistoryBtn'),phaseCard:$('phaseCard'),roundLabel:$('roundLabel'),gpsStatus:$('gpsStatus'),ringProgress:$('ringProgress'),activityEmoji:$('activityEmoji'),phaseName:$('phaseName'),countdown:$('countdown'),nextLabel:$('nextLabel'),totalDistance:$('totalDistance'),walkDistance:$('walkDistance'),runDistance:$('runDistance'),elapsedTime:$('elapsedTime'),cycleCount:$('cycleCount'),paceValue:$('paceValue'),walkTime:$('walkTime'),runTime:$('runTime'),caloriesValue:$('caloriesValue'),editIntervalsBtn:$('editIntervalsBtn'),stopBtn:$('stopBtn'),pauseBtn:$('pauseBtn'),summaryDistance:$('summaryDistance'),summaryDuration:$('summaryDuration'),summaryCycles:$('summaryCycles'),summaryWalkDistance:$('summaryWalkDistance'),summaryRunDistance:$('summaryRunDistance'),summaryWalkTime:$('summaryWalkTime'),summaryRunTime:$('summaryRunTime'),summaryPace:$('summaryPace'),summaryCalories:$('summaryCalories'),newWorkoutBtn:$('newWorkoutBtn'),historyCount:$('historyCount'),historyDistance:$('historyDistance'),historyTime:$('historyTime'),historyList:$('historyList'),clearHistoryBtn:$('clearHistoryBtn'),editModal:$('editModal'),closeEditBtn:$('closeEditBtn'),liveWalkMinutes:$('liveWalkMinutes'),liveWalkSeconds:$('liveWalkSeconds'),liveRunMinutes:$('liveRunMinutes'),liveRunSeconds:$('liveRunSeconds'),applyCurrentPhase:$('applyCurrentPhase'),applyIntervalsBtn:$('applyIntervalsBtn'),toast:$('toast')};
const C=2*Math.PI*112;let previousView='setupView';let s={walkDuration:120,runDuration:180,phase:'walk',phaseDuration:120,remaining:120,elapsed:0,walkElapsed:0,runElapsed:0,cycles:0,round:1,active:false,paused:false,sound:true,timer:null,end:0,lastTick:0,audio:null,wake:null,gps:true,watch:null,lastPos:null,totalM:0,walkM:0,runM:0,speed:null,weight:75,startedAt:null};
const views=['setupView','timerView','summaryView','historyView'];function show(v){views.forEach(x=>E[x].classList.toggle('active',x===v));if(v!=='historyView')previousView=v}
const clamp=(v,a,b)=>Math.min(b,Math.max(a,Number(v)||0));function fmt(n){n=Math.max(0,Math.ceil(n));return`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}const km=m=>`${(m/1000).toFixed(2)} km`;
function pace(v){if(!v||v<.45)return'--';let x=1000/v;if(!isFinite(x)||x>3600)return'--';return`${Math.floor(x/60)}:${String(Math.round(x%60)).padStart(2,'0')}/km`}
function avgPace(){if(s.totalM<50||s.elapsed<30)return'--';let x=s.elapsed/(s.totalM/1000);return`${Math.floor(x/60)}:${String(Math.round(x%60)).padStart(2,'0')}/km`}
function calories(){let wh=s.walkElapsed/3600,rh=s.runElapsed/3600;return Math.round((3.5*s.weight*wh)+(8.3*s.weight*rh))}
function toast(t){E.toast.textContent=t;E.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>E.toast.classList.remove('show'),2600)}
function beep(){try{s.audio??=new(AudioContext||webkitAudioContext);s.audio.resume();let n=s.audio.currentTime;[[0,740],[.19,920],[.38,1120]].forEach(([t,f])=>{let o=s.audio.createOscillator(),g=s.audio.createGain();o.type='square';o.frequency.value=f;g.gain.setValueAtTime(.0001,n+t);g.gain.exponentialRampToValueAtTime(.18,n+t+.015);g.gain.exponentialRampToValueAtTime(.0001,n+t+.2);o.connect(g);g.connect(s.audio.destination);o.start(n+t);o.stop(n+t+.23)})}catch(e){}}
function say(t){toast(t);if(!s.sound)return;beep();if('speechSynthesis'in window){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.volume=1;speechSynthesis.speak(u)}navigator.vibrate?.([220,90,220,90,300])}
async function wake(){try{s.wake=await navigator.wakeLock?.request('screen')}catch(e){}}async function unwake(){try{await s.wake?.release()}catch(e){}s.wake=null}
function hav(a,b){let r=x=>x*Math.PI/180,R=6371000,d1=r(b.latitude-a.latitude),d2=r(b.longitude-a.longitude),q=Math.sin(d1/2)**2+Math.cos(r(a.latitude))*Math.cos(r(b.latitude))*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function stopGps(){if(s.watch!==null)navigator.geolocation?.clearWatch(s.watch);s.watch=null;s.lastPos=null}
function startGps(){stopGps();if(!s.gps){E.gpsStatus.textContent='GPS off';return}if(!navigator.geolocation){E.gpsStatus.textContent='GPS unavailable';return}E.gpsStatus.textContent='Requesting GPS…';s.watch=navigator.geolocation.watchPosition(p=>{let c=p.coords,n={latitude:c.latitude,longitude:c.longitude,accuracy:c.accuracy,timestamp:p.timestamp};E.gpsStatus.textContent=c.accuracy<=20?`GPS ±${Math.round(c.accuracy)} m`:'GPS weak';if(s.active&&!s.paused&&s.lastPos&&c.accuracy<=50&&s.lastPos.accuracy<=50){let d=hav(s.lastPos,n),dt=Math.max(1,(n.timestamp-s.lastPos.timestamp)/1000);if(d>=1.2&&d<=Math.max(70,dt*12)){s.totalM+=d;s.phase==='walk'?s.walkM+=d:s.runM+=d}}s.speed=Number.isFinite(c.speed)&&c.speed>=0?c.speed:s.lastPos?hav(s.lastPos,n)/Math.max(1,(n.timestamp-s.lastPos.timestamp)/1000):null;s.lastPos=n;renderMetrics()},()=>{E.gpsStatus.textContent='GPS unavailable';toast('GPS unavailable. Timer still works.')},{enableHighAccuracy:true,maximumAge:1000,timeout:15000})}
function readDuration(m,sx){m.value=clamp(m.value,0,99);sx.value=clamp(sx.value,0,59);return Number(m.value)*60+Number(sx.value)}
function setInputs(total,m,sx){m.value=Math.floor(total/60);sx.value=total%60}
function renderMetrics(){E.totalDistance.textContent=km(s.totalM);E.walkDistance.textContent=km(s.walkM);E.runDistance.textContent=km(s.runM);E.paceValue.textContent=pace(s.speed);E.walkTime.textContent=fmt(s.walkElapsed);E.runTime.textContent=fmt(s.runElapsed);E.caloriesValue.textContent=`${calories()} kcal`}
function phaseUI(){let w=s.phase==='walk';E.phaseCard.className=`phase-card ${w?'walking':'running'}`;E.activityEmoji.textContent=w?'🚶':'🏃';E.phaseName.textContent=w?'WALK':'RUN';E.roundLabel.textContent=`ROUND ${s.round}`;E.nextLabel.textContent=w?`Next: Run ${fmt(s.runDuration)}`:`Next: Walk ${fmt(s.walkDuration)}`}
function render(){E.countdown.textContent=fmt(s.remaining);E.elapsedTime.textContent=fmt(s.elapsed);E.cycleCount.textContent=s.cycles;let p=s.phaseDuration?Math.max(0,Math.min(1,s.remaining/s.phaseDuration)):0;E.ringProgress.style.strokeDasharray=C;E.ringProgress.style.strokeDashoffset=C*(1-p);document.title=`${fmt(s.remaining)} · ${s.phase}`;renderMetrics()}
function switchPhase(){if(s.phase==='walk'){s.phase='run';s.phaseDuration=s.runDuration;s.remaining=s.runDuration;say('Start running')}else{s.phase='walk';s.phaseDuration=s.walkDuration;s.remaining=s.walkDuration;s.cycles++;s.round++;say('Start walking')}s.end=Date.now()+s.remaining*1000;s.lastTick=Date.now();phaseUI();render()}
function tick(){if(!s.active||s.paused)return;let n=Date.now(),d=Math.max(0,(n-s.lastTick)/1000);s.elapsed+=d;s.phase==='walk'?s.walkElapsed+=d:s.runElapsed+=d;s.lastTick=n;s.remaining=Math.max(0,(s.end-n)/1000);s.remaining<=.02?switchPhase():render()}
function start(){s.walkDuration=readDuration(E.walkMinutes,E.walkSeconds);s.runDuration=readDuration(E.runMinutes,E.runSeconds);if(s.walkDuration<1||s.runDuration<1)return toast('Each interval must be at least 1 second.');s.gps=E.gpsToggle.checked;s.weight=clamp(E.weightKg.value,30,250)||75;Object.assign(s,{phase:'walk',phaseDuration:s.walkDuration,remaining:s.walkDuration,elapsed:0,walkElapsed:0,runElapsed:0,cycles:0,round:1,active:true,paused:false,totalM:0,walkM:0,runM:0,speed:null,lastPos:null,startedAt:new Date().toISOString()});show('timerView');phaseUI();render();s.end=Date.now()+s.remaining*1000;s.lastTick=Date.now();clearInterval(s.timer);s.timer=setInterval(tick,200);wake();startGps();say('Start walking')}
function pause(){if(!s.active)return;s.paused=!s.paused;if(s.paused){s.remaining=Math.max(0,(s.end-Date.now())/1000);E.pauseBtn.textContent='▶ Resume';say('Workout paused')}else{s.end=Date.now()+s.remaining*1000;s.lastTick=Date.now();E.pauseBtn.textContent='Ⅱ Pause';say(s.phase==='walk'?'Continue walking':'Continue running')}render()}
function saveHistory(){let h=JSON.parse(localStorage.getItem('touraysHistory')||'[]');h.unshift({date:new Date().toISOString(),duration:s.elapsed,distance:s.totalM,walkDistance:s.walkM,runDistance:s.runM,walkTime:s.walkElapsed,runTime:s.runElapsed,cycles:s.cycles,calories:calories(),pace:avgPace()});localStorage.setItem('touraysHistory',JSON.stringify(h.slice(0,50)))}
function stop(){s.active=false;s.paused=false;clearInterval(s.timer);stopGps();unwake();speechSynthesis?.cancel();E.summaryDistance.textContent=km(s.totalM);E.summaryDuration.textContent=fmt(s.elapsed);E.summaryCycles.textContent=s.cycles;E.summaryWalkDistance.textContent=km(s.walkM);E.summaryRunDistance.textContent=km(s.runM);E.summaryWalkTime.textContent=fmt(s.walkElapsed);E.summaryRunTime.textContent=fmt(s.runElapsed);E.summaryPace.textContent=avgPace();E.summaryCalories.textContent=`${calories()} kcal`;saveHistory();document.title='Tourays Walk & Run';show('summaryView')}
function openEdit(){setInputs(s.walkDuration,E.liveWalkMinutes,E.liveWalkSeconds);setInputs(s.runDuration,E.liveRunMinutes,E.liveRunSeconds);E.applyCurrentPhase.checked=false;E.editModal.classList.add('open');E.editModal.setAttribute('aria-hidden','false')}
function closeEdit(){E.editModal.classList.remove('open');E.editModal.setAttribute('aria-hidden','true')}
function applyIntervals(){let nw=readDuration(E.liveWalkMinutes,E.liveWalkSeconds),nr=readDuration(E.liveRunMinutes,E.liveRunSeconds);if(nw<1||nr<1)return toast('Each interval must be at least 1 second.');s.walkDuration=nw;s.runDuration=nr;if(E.applyCurrentPhase.checked){let nd=s.phase==='walk'?nw:nr;s.phaseDuration=nd;s.remaining=nd;s.end=Date.now()+nd*1000;s.lastTick=Date.now()}phaseUI();render();closeEdit();say('New intervals applied')}
function renderHistory(){let h=JSON.parse(localStorage.getItem('touraysHistory')||'[]');E.historyCount.textContent=h.length;E.historyDistance.textContent=km(h.reduce((a,x)=>a+(x.distance||0),0));E.historyTime.textContent=fmt(h.reduce((a,x)=>a+(x.duration||0),0));E.historyList.innerHTML=h.length?h.map(x=>`<article class="history-item"><div class="history-item-head"><strong>${new Date(x.date).toLocaleDateString()}</strong><small>${new Date(x.date).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small></div><div class="history-item-grid"><div><span>Time</span><strong>${fmt(x.duration)}</strong></div><div><span>Distance</span><strong>${km(x.distance)}</strong></div><div><span>Calories</span><strong>${x.calories} kcal</strong></div></div></article>`).join(''):'<p class="hint">No saved workouts yet.</p>'}
document.querySelectorAll('.presets button').forEach(b=>b.onclick=()=>{let w=+b.dataset.w,r=+b.dataset.r;setInputs(w,E.walkMinutes,E.walkSeconds);setInputs(r,E.runMinutes,E.runSeconds);document.querySelectorAll('.presets button').forEach(x=>x.classList.toggle('selected',x===b))});
[E.walkMinutes,E.walkSeconds,E.runMinutes,E.runSeconds].forEach(i=>i.oninput=()=>document.querySelectorAll('.presets button').forEach(x=>x.classList.remove('selected')));
E.savePresetBtn.onclick=()=>{localStorage.setItem('touraysPreset',JSON.stringify({w:readDuration(E.walkMinutes,E.walkSeconds),r:readDuration(E.runMinutes,E.runSeconds)}));toast('Custom workout saved')};
E.loadPresetBtn.onclick=()=>{let p=JSON.parse(localStorage.getItem('touraysPreset')||'null');if(!p)return toast('No saved workout found');setInputs(p.w,E.walkMinutes,E.walkSeconds);setInputs(p.r,E.runMinutes,E.runSeconds);toast('Saved workout loaded')};
E.startBtn.onclick=start;E.pauseBtn.onclick=pause;E.stopBtn.onclick=stop;E.newWorkoutBtn.onclick=()=>show('setupView');E.editIntervalsBtn.onclick=openEdit;E.closeEditBtn.onclick=closeEdit;E.applyIntervalsBtn.onclick=applyIntervals;
E.soundBtn.onclick=()=>{s.sound=!s.sound;E.soundBtn.textContent=s.sound?'🔊':'🔇';toast(s.sound?'Sound enabled':'Sound disabled')};
E.historyBtn.onclick=()=>{previousView=views.find(v=>E[v].classList.contains('active'))||'setupView';renderHistory();show('historyView')};E.closeHistoryBtn.onclick=()=>show(previousView);E.clearHistoryBtn.onclick=()=>{localStorage.removeItem('touraysHistory');renderHistory();toast('History cleared')};
E.editModal.onclick=e=>{if(e.target===E.editModal)closeEdit()};
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&s.active&&!s.paused){s.remaining=Math.max(0,(s.end-Date.now())/1000);s.lastTick=Date.now();s.remaining<=.02?switchPhase():render();wake()}});
window.addEventListener('beforeunload',()=>{stopGps();unwake()});if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));