const $=id=>document.getElementById(id),E={homePage:$('homePage'),workoutPage:$('workoutPage'),historyPage:$('historyPage'),settingsPage:$('settingsPage'),soundBtn:$('soundBtn'),walkMinutes:$('walkMinutes'),walkSeconds:$('walkSeconds'),runMinutes:$('runMinutes'),runSeconds:$('runSeconds'),startBtn:$('startBtn'),phaseCard:$('phaseCard'),roundLabel:$('roundLabel'),gpsStatus:$('gpsStatus'),ringProgress:$('ringProgress'),activityEmoji:$('activityEmoji'),phaseName:$('phaseName'),countdown:$('countdown'),nextLabel:$('nextLabel'),totalDistance:$('totalDistance'),walkDistance:$('walkDistance'),runDistance:$('runDistance'),elapsedTime:$('elapsedTime'),cycleCount:$('cycleCount'),paceValue:$('paceValue'),editIntervalsBtn:$('editIntervalsBtn'),stopBtn:$('stopBtn'),pauseBtn:$('pauseBtn'),historyCount:$('historyCount'),historyDistance:$('historyDistance'),historyTime:$('historyTime'),historyList:$('historyList'),gpsToggle:$('gpsToggle'),weightKg:$('weightKg'),savePlanBtn:$('savePlanBtn'),loadPlanBtn:$('loadPlanBtn'),editModal:$('editModal'),closeEditBtn:$('closeEditBtn'),liveWalkMinutes:$('liveWalkMinutes'),liveWalkSeconds:$('liveWalkSeconds'),liveRunMinutes:$('liveRunMinutes'),liveRunSeconds:$('liveRunSeconds'),applyCurrentPhase:$('applyCurrentPhase'),applyIntervalsBtn:$('applyIntervalsBtn'),toast:$('toast')};const C=2*Math.PI*112;let s={walk:120,run:180,phase:'walk',duration:120,left:120,elapsed:0,cycles:0,active:false,paused:false,sound:true,timer:null,end:0,last:0,audio:null,gps:true,watch:null,pos:null,total:0,walkM:0,runM:0,speed:null};
const pages=['homePage','workoutPage','historyPage','settingsPage'];function showPage(id){pages.forEach(p=>E[p].classList.toggle('active',p===id));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===id));if(id==='historyPage')renderHistory()}
const clamp=(v,a,b)=>Math.min(b,Math.max(a,Number(v)||0));function fmt(n){n=Math.max(0,Math.ceil(n));return`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}const km=m=>`${(m/1000).toFixed(2)} km`;function pace(v){if(!v||v<.45)return'--';let x=1000/v;if(!isFinite(x)||x>3600)return'--';return`${Math.floor(x/60)}:${String(Math.round(x%60)).padStart(2,'0')}/km`}
function toast(t){E.toast.textContent=t;E.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>E.toast.classList.remove('show'),2400)}
function beep(){try{s.audio??=new(AudioContext||webkitAudioContext);s.audio.resume();let n=s.audio.currentTime;[[0,740],[.18,930],[.36,1120]].forEach(([t,f])=>{let o=s.audio.createOscillator(),g=s.audio.createGain();o.type='square';o.frequency.value=f;g.gain.setValueAtTime(.0001,n+t);g.gain.exponentialRampToValueAtTime(.18,n+t+.015);g.gain.exponentialRampToValueAtTime(.0001,n+t+.18);o.connect(g);g.connect(s.audio.destination);o.start(n+t);o.stop(n+t+.22)})}catch(e){}}
function say(t){toast(t);if(!s.sound)return;beep();if('speechSynthesis'in window){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);speechSynthesis.speak(u)}navigator.vibrate?.([200,80,200])}
function readDur(m,sec){m.value=clamp(m.value,0,99);sec.value=clamp(sec.value,0,59);return Number(m.value)*60+Number(sec.value)}function setDur(total,m,sec){m.value=Math.floor(total/60);sec.value=total%60}
function hav(a,b){let r=x=>x*Math.PI/180,R=6371000,d1=r(b.latitude-a.latitude),d2=r(b.longitude-a.longitude),q=Math.sin(d1/2)**2+Math.cos(r(a.latitude))*Math.cos(r(b.latitude))*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function stopGps(){if(s.watch!==null)navigator.geolocation?.clearWatch(s.watch);s.watch=null;s.pos=null}
function startGps(){stopGps();if(!s.gps){E.gpsStatus.textContent='GPS off';return}if(!navigator.geolocation){E.gpsStatus.textContent='GPS unavailable';return}E.gpsStatus.textContent='Requesting GPS…';s.watch=navigator.geolocation.watchPosition(p=>{let c=p.coords,n={latitude:c.latitude,longitude:c.longitude,accuracy:c.accuracy,timestamp:p.timestamp};E.gpsStatus.textContent=c.accuracy<=20?`GPS ±${Math.round(c.accuracy)}m`:'GPS weak';if(s.active&&!s.paused&&s.pos&&c.accuracy<=50&&s.pos.accuracy<=50){let d=hav(s.pos,n),dt=Math.max(1,(n.timestamp-s.pos.timestamp)/1000);if(d>=1.2&&d<=Math.max(70,dt*12)){s.total+=d;s.phase==='walk'?s.walkM+=d:s.runM+=d}}s.speed=Number.isFinite(c.speed)&&c.speed>=0?c.speed:s.pos?hav(s.pos,n)/Math.max(1,(n.timestamp-s.pos.timestamp)/1000):null;s.pos=n;render()},()=>{E.gpsStatus.textContent='GPS unavailable'},{enableHighAccuracy:true,maximumAge:1000,timeout:15000})}
function phaseUI(){let w=s.phase==='walk';E.phaseCard.className=`phase-card ${w?'walking':'running'}`;E.activityEmoji.textContent=w?'🚶':'🏃';E.phaseName.textContent=w?'WALK':'RUN';E.roundLabel.textContent=`ROUND ${s.cycles+1}`;E.nextLabel.textContent=w?`Next: Run ${fmt(s.run)}`:`Next: Walk ${fmt(s.walk)}`}
function render(){E.countdown.textContent=fmt(s.left);E.elapsedTime.textContent=fmt(s.elapsed);E.cycleCount.textContent=s.cycles;E.totalDistance.textContent=km(s.total);E.walkDistance.textContent=km(s.walkM);E.runDistance.textContent=km(s.runM);E.paceValue.textContent=pace(s.speed);let p=s.duration?Math.max(0,Math.min(1,s.left/s.duration)):0;E.ringProgress.style.strokeDasharray=C;E.ringProgress.style.strokeDashoffset=C*(1-p)}
function switchPhase(){if(s.phase==='walk'){s.phase='run';s.duration=s.run;s.left=s.run;say('Start running')}else{s.phase='walk';s.duration=s.walk;s.left=s.walk;s.cycles++;say('Start walking')}s.end=Date.now()+s.left*1000;s.last=Date.now();phaseUI();render()}
function tick(){if(!s.active||s.paused)return;let n=Date.now();s.elapsed+=Math.max(0,(n-s.last)/1000);s.last=n;s.left=Math.max(0,(s.end-n)/1000);s.left<=.02?switchPhase():render()}
function start(){s.walk=readDur(E.walkMinutes,E.walkSeconds);s.run=readDur(E.runMinutes,E.runSeconds);if(s.walk<1||s.run<1)return toast('Each interval must be at least 1 second.');s.gps=E.gpsToggle.checked;Object.assign(s,{phase:'walk',duration:s.walk,left:s.walk,elapsed:0,cycles:0,active:true,paused:false,total:0,walkM:0,runM:0,speed:null,pos:null});showPage('workoutPage');phaseUI();render();s.end=Date.now()+s.left*1000;s.last=Date.now();clearInterval(s.timer);s.timer=setInterval(tick,200);startGps();say('Start walking')}
function pause(){if(!s.active)return;s.paused=!s.paused;if(s.paused){s.left=Math.max(0,(s.end-Date.now())/1000);E.pauseBtn.textContent='▶ Resume';say('Workout paused')}else{s.end=Date.now()+s.left*1000;s.last=Date.now();E.pauseBtn.textContent='Ⅱ Pause';say(s.phase==='walk'?'Continue walking':'Continue running')}render()}
function stop(){s.active=false;s.paused=false;clearInterval(s.timer);stopGps();speechSynthesis?.cancel();let h=JSON.parse(localStorage.getItem('touraysHistory')||'[]');h.unshift({date:new Date().toISOString(),duration:s.elapsed,distance:s.total,cycles:s.cycles});localStorage.setItem('touraysHistory',JSON.stringify(h.slice(0,30)));showPage('historyPage');toast('Workout saved')}
function openEdit(){setDur(s.walk,E.liveWalkMinutes,E.liveWalkSeconds);setDur(s.run,E.liveRunMinutes,E.liveRunSeconds);E.applyCurrentPhase.checked=false;E.editModal.classList.add('open')}
function closeEdit(){E.editModal.classList.remove('open')}
function applyEdit(){let w=readDur(E.liveWalkMinutes,E.liveWalkSeconds),r=readDur(E.liveRunMinutes,E.liveRunSeconds);if(w<1||r<1)return toast('Each interval must be at least 1 second.');s.walk=w;s.run=r;if(E.applyCurrentPhase.checked){s.duration=s.phase==='walk'?w:r;s.left=s.duration;s.end=Date.now()+s.left*1000;s.last=Date.now()}phaseUI();render();closeEdit();say('New intervals applied')}
function renderHistory(){let h=JSON.parse(localStorage.getItem('touraysHistory')||'[]');E.historyCount.textContent=h.length;E.historyDistance.textContent=km(h.reduce((a,x)=>a+(x.distance||0),0));E.historyTime.textContent=fmt(h.reduce((a,x)=>a+(x.duration||0),0));E.historyList.innerHTML=h.length?h.map(x=>`<article class="history-item"><div class="history-item-head"><strong>${new Date(x.date).toLocaleDateString()}</strong><small>${new Date(x.date).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small></div><div class="history-item-grid"><div><span>Time</span><strong>${fmt(x.duration)}</strong></div><div><span>Distance</span><strong>${km(x.distance)}</strong></div><div><span>Cycles</span><strong>${x.cycles}</strong></div></div></article>`).join(''):'<p style="color:#9eabc0">No workouts yet.</p>'}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>showPage(b.dataset.page));document.querySelectorAll('.preset-card').forEach(b=>b.onclick=()=>{setDur(+b.dataset.w,E.walkMinutes,E.walkSeconds);setDur(+b.dataset.r,E.runMinutes,E.runSeconds);document.querySelectorAll('.preset-card').forEach(x=>x.classList.toggle('selected',x===b))});
E.startBtn.onclick=start;E.pauseBtn.onclick=pause;E.stopBtn.onclick=stop;E.editIntervalsBtn.onclick=openEdit;E.closeEditBtn.onclick=closeEdit;E.applyIntervalsBtn.onclick=applyEdit;E.soundBtn.onclick=()=>{s.sound=!s.sound;E.soundBtn.textContent=s.sound?'🔊':'🔇'};E.savePlanBtn.onclick=()=>{localStorage.setItem('touraysPlan',JSON.stringify({w:readDur(E.walkMinutes,E.walkSeconds),r:readDur(E.runMinutes,E.runSeconds)}));toast('Plan saved')};E.loadPlanBtn.onclick=()=>{let p=JSON.parse(localStorage.getItem('touraysPlan')||'null');if(!p)return toast('No saved plan');setDur(p.w,E.walkMinutes,E.walkSeconds);setDur(p.r,E.runMinutes,E.runSeconds);showPage('homePage');toast('Plan loaded')};E.editModal.onclick=e=>{if(e.target===E.editModal)closeEdit()};if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));