
const $=id=>document.getElementById(id),C=2*Math.PI*112;
const E={wm:$('wm'),ws:$('ws'),rm:$('rm'),rs:$('rs'),runSetup:$('runSetup'),runActive:$('runActive'),startRun:$('startRun'),timerCard:$('timerCard'),round:$('round'),gpsStatus:$('gpsStatus'),ringProgress:$('ringProgress'),phaseEmoji:$('phaseEmoji'),phaseName:$('phaseName'),countdown:$('countdown'),nextLabel:$('nextLabel'),totalDistance:$('totalDistance'),walkDistance:$('walkDistance'),runDistance:$('runDistance'),elapsed:$('elapsed'),cycles:$('cycles'),pace:$('pace'),changeIntervals:$('changeIntervals'),stopRun:$('stopRun'),pauseRun:$('pauseRun'),soundBtn:$('soundBtn'),settingsBtn:$('settingsBtn'),exerciseGrid:$('exerciseGrid'),demo:$('demo'),exerciseName:$('exerciseName'),exerciseTarget:$('exerciseTarget'),exerciseTip:$('exerciseTip'),exerciseAmount:$('exerciseAmount'),exerciseUnit:$('exerciseUnit'),lessExercise:$('lessExercise'),moreExercise:$('moreExercise'),startExercise:$('startExercise'),mapDistance:$('mapDistance'),mapAccuracy:$('mapAccuracy'),recenterMap:$('recenterMap'),routeHome:$('routeHome'),directions:$('directions'),routeDistance:$('routeDistance'),routeDuration:$('routeDuration'),directionSteps:$('directionSteps'),weeklyMinutes:$('weeklyMinutes'),weeklyMessage:$('weeklyMessage'),goalProgress:$('goalProgress'),goalPercent:$('goalPercent'),healthCalories:$('healthCalories'),healthDistance:$('healthDistance'),healthBmi:$('healthBmi'),bmiLabel:$('bmiLabel'),healthPace:$('healthPace'),historyList:$('historyList'),intervalModal:$('intervalModal'),closeIntervals:$('closeIntervals'),lwm:$('lwm'),lws:$('lws'),lrm:$('lrm'),lrs:$('lrs'),applyNow:$('applyNow'),applyIntervals:$('applyIntervals'),settingsModal:$('settingsModal'),closeSettings:$('closeSettings'),gpsToggle:$('gpsToggle'),weight:$('weight'),height:$('height'),weeklyGoal:$('weeklyGoal'),toast:$('toast')};
let S={walk:120,run:180,phase:'walk',duration:120,left:120,elapsed:0,walkTime:0,runTime:0,cycles:0,active:false,paused:false,sound:true,timer:null,end:0,last:0,audio:null,gps:true,watch:null,pos:null,start:null,total:0,walkM:0,runM:0,speed:null,map:null,userMarker:null,startMarker:null,trace:[],routeGeo:null,indoorTimer:null};
const exercises=[
{name:'Push-ups',icon:'💪',amount:10,unit:'repetitions',tip:'Keep a straight line from shoulders to heels. Lower your chest between your hands.',type:'push'},
{name:'Squats',icon:'🦵',amount:15,unit:'repetitions',tip:'Sit your hips back, keep your chest lifted and track knees over toes.',type:'squat'},
{name:'Sit-ups',icon:'🧘',amount:12,unit:'repetitions',tip:'Brace your core and rise smoothly. Do not pull your head with your hands.',type:'sit'},
{name:'Lunges',icon:'🚶',amount:10,unit:'each leg',tip:'Take a stable step, keep your front knee aligned and lower the back knee.',type:'lunge'},
{name:'Plank',icon:'⏱️',amount:30,unit:'seconds',tip:'Brace your core and keep shoulders, hips and heels in one straight line.',type:'plank'},
{name:'Mountain climbers',icon:'🏔️',amount:30,unit:'seconds',tip:'Keep shoulders above hands and alternate knees without bouncing your hips.',type:'climber'},
{name:'Burpees',icon:'🔥',amount:8,unit:'repetitions',tip:'Move through squat, plank and stand with control. Land softly.',type:'burpee'},
{name:'Jumping jacks',icon:'⭐',amount:30,unit:'seconds',tip:'Land softly and keep a steady rhythm while arms and legs move together.',type:'jack'}
];let currentExercise=0,exerciseAmount=10;
const clamp=(v,a,b)=>Math.min(b,Math.max(a,Number(v)||0));function fmt(n){n=Math.max(0,Math.ceil(n));return`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}const km=m=>`${(m/1000).toFixed(2)} km`;function pace(v){if(!v||v<.45)return'--';const x=1000/v;if(!isFinite(x)||x>3600)return'--';return`${Math.floor(x/60)}:${String(Math.round(x%60)).padStart(2,'0')}/km`}
function show(name){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===name));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.screen===name));if(name==='mapScreen')setTimeout(()=>{initMap();S.map?.resize()},80);if(name==='health')renderHealth()}
function toast(t){E.toast.textContent=t;E.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>E.toast.classList.remove('show'),2300)}
function beep(){try{S.audio??=new(AudioContext||webkitAudioContext);S.audio.resume();const n=S.audio.currentTime;[[0,760],[.18,960]].forEach(([t,f])=>{const o=S.audio.createOscillator(),g=S.audio.createGain();o.frequency.value=f;g.gain.setValueAtTime(.0001,n+t);g.gain.exponentialRampToValueAtTime(.2,n+t+.02);g.gain.exponentialRampToValueAtTime(.0001,n+t+.17);o.connect(g);g.connect(S.audio.destination);o.start(n+t);o.stop(n+t+.2)})}catch{}}
function say(t){toast(t);if(!S.sound)return;beep();if('speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(t))}navigator.vibrate?.([180,80,180])}
function read(m,s){m.value=clamp(m.value,0,99);s.value=clamp(s.value,0,59);return Number(m.value)*60+Number(s.value)}function setTime(n,m,s){m.value=Math.floor(n/60);s.value=n%60}
function hav(a,b){const r=x=>x*Math.PI/180,R=6371000,d1=r(b.latitude-a.latitude),d2=r(b.longitude-a.longitude),q=Math.sin(d1/2)**2+Math.cos(r(a.latitude))*Math.cos(r(b.latitude))*Math.sin(d2/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function initMap(){if(S.map||typeof maplibregl==='undefined')return;S.map=new maplibregl.Map({container:'map',style:'https://tiles.openfreemap.org/styles/liberty',center:[9.1829,48.7758],zoom:13,pitch:35,attributionControl:true});S.map.addControl(new maplibregl.NavigationControl({visualizePitch:true}),'bottom-right');S.map.on('load',()=>{S.map.addSource('trace',{type:'geojson',data:{type:'Feature',geometry:{type:'LineString',coordinates:[]}}});S.map.addLayer({id:'trace-line',type:'line',source:'trace',paint:{'line-color':'#8d7cff','line-width':6,'line-opacity':.9}});S.map.addSource('route-home',{type:'geojson',data:{type:'Feature',geometry:{type:'LineString',coordinates:[]}}});S.map.addLayer({id:'route-home-line',type:'line',source:'route-home',paint:{'line-color':'#42d5a1','line-width':7,'line-opacity':.92,'line-dasharray':[1.2,1.2]}})})}
function updateMap(p,accuracy){initMap();if(!S.map)return;const lngLat=[p.longitude,p.latitude];if(!S.userMarker){const node=document.createElement('div');node.style.cssText='width:19px;height:19px;border-radius:50%;background:#8d7cff;border:4px solid white;box-shadow:0 3px 12px #0008';S.userMarker=new maplibregl.Marker({element:node}).setLngLat(lngLat).addTo(S.map)}else S.userMarker.setLngLat(lngLat);if(!S.start){S.start=p;const node=document.createElement('div');node.textContent='🏁';node.style.fontSize='24px';S.startMarker=new maplibregl.Marker({element:node}).setLngLat(lngLat).addTo(S.map);S.map.flyTo({center:lngLat,zoom:16,pitch:45})}S.trace.push(lngLat);const src=S.map.getSource('trace');if(src)src.setData({type:'Feature',geometry:{type:'LineString',coordinates:S.trace}});E.mapDistance.textContent=`From start: ${S.start?km(hav(S.start,p)):'--'}`;E.mapAccuracy.textContent=`GPS: ±${Math.round(accuracy)} m`}
function stopGps(){if(S.watch!==null)navigator.geolocation?.clearWatch(S.watch);S.watch=null;S.pos=null}
function startGps(){stopGps();if(!S.gps||!navigator.geolocation){E.gpsStatus.textContent='GPS off';return}E.gpsStatus.textContent='Finding GPS…';S.watch=navigator.geolocation.watchPosition(x=>{const c=x.coords,p={latitude:c.latitude,longitude:c.longitude,accuracy:c.accuracy,timestamp:x.timestamp};E.gpsStatus.textContent=c.accuracy<=20?`GPS ±${Math.round(c.accuracy)}m`:'GPS weak';if(S.active&&!S.paused&&S.pos&&c.accuracy<=50&&S.pos.accuracy<=50){const d=hav(S.pos,p),dt=Math.max(1,(p.timestamp-S.pos.timestamp)/1000);if(d>=1.2&&d<=Math.max(70,dt*12)){S.total+=d;S.phase==='walk'?S.walkM+=d:S.runM+=d}}S.speed=Number.isFinite(c.speed)&&c.speed>=0?c.speed:S.pos?hav(S.pos,p)/Math.max(1,(p.timestamp-S.pos.timestamp)/1000):null;S.pos=p;updateMap(p,c.accuracy);renderRun()},()=>E.gpsStatus.textContent='GPS unavailable',{enableHighAccuracy:true,maximumAge:1000,timeout:15000})}
function phaseUI(){const w=S.phase==='walk';E.timerCard.className=`timer-card ${w?'walking':'running'}`;E.phaseEmoji.textContent=w?'🚶':'🏃';E.phaseName.textContent=w?'WALK':'RUN';E.round.textContent=`ROUND ${S.cycles+1}`;E.nextLabel.textContent=w?`Next: Run ${fmt(S.run)}`:`Next: Walk ${fmt(S.walk)}`}
function renderRun(){E.countdown.textContent=fmt(S.left);E.elapsed.textContent=fmt(S.elapsed);E.cycles.textContent=S.cycles;E.totalDistance.textContent=km(S.total);E.walkDistance.textContent=km(S.walkM);E.runDistance.textContent=km(S.runM);E.pace.textContent=pace(S.speed);const p=S.duration?Math.max(0,Math.min(1,S.left/S.duration)):0;E.ringProgress.style.strokeDasharray=C;E.ringProgress.style.strokeDashoffset=C*(1-p)}
function switchPhase(){if(S.phase==='walk'){S.phase='run';S.duration=S.run;S.left=S.run;say('Start running')}else{S.phase='walk';S.duration=S.walk;S.left=S.walk;S.cycles++;say('Start walking')}S.end=Date.now()+S.left*1000;S.last=Date.now();phaseUI();renderRun()}
function tick(){if(!S.active||S.paused)return;const n=Date.now(),d=Math.max(0,(n-S.last)/1000);S.elapsed+=d;S.phase==='walk'?S.walkTime+=d:S.runTime+=d;S.last=n;S.left=Math.max(0,(S.end-n)/1000);S.left<=.02?switchPhase():renderRun()}
function startRun(){S.walk=read(E.wm,E.ws);S.run=read(E.rm,E.rs);if(S.walk<1||S.run<1)return toast('Each interval must be at least 1 second');S.gps=E.gpsToggle.checked;Object.assign(S,{phase:'walk',duration:S.walk,left:S.walk,elapsed:0,walkTime:0,runTime:0,cycles:0,active:true,paused:false,total:0,walkM:0,runM:0,speed:null,pos:null,start:null,trace:[]});E.runSetup.hidden=true;E.runActive.hidden=false;phaseUI();renderRun();S.end=Date.now()+S.left*1000;S.last=Date.now();clearInterval(S.timer);S.timer=setInterval(tick,200);startGps();say('Start walking')}
function pauseRun(){if(!S.active)return;S.paused=!S.paused;if(S.paused){S.left=Math.max(0,(S.end-Date.now())/1000);E.pauseRun.textContent='▶ Resume';say('Workout paused')}else{S.end=Date.now()+S.left*1000;S.last=Date.now();E.pauseRun.textContent='Ⅱ Pause';say(S.phase==='walk'?'Continue walking':'Continue running')}renderRun()}
function estimateCalories(){const w=clamp(E.weight.value,30,250)||75;return Math.round((3.5*w*S.walkTime/3600)+(8.3*w*S.runTime/3600))}
function stopRun(){if(!S.active)return;S.active=false;S.paused=false;clearInterval(S.timer);stopGps();const h=history();h.unshift({type:'Walk & Run',date:new Date().toISOString(),duration:S.elapsed,distance:S.total,cycles:S.cycles,calories:estimateCalories(),walk:S.walk,run:S.run});saveHistory(h);E.runSetup.hidden=false;E.runActive.hidden=true;show('health');toast('Workout saved')}
function openIntervals(){setTime(S.walk,E.lwm,E.lws);setTime(S.run,E.lrm,E.lrs);E.applyNow.checked=false;E.intervalModal.classList.add('open')}function applyIntervals(){const w=read(E.lwm,E.lws),r=read(E.lrm,E.lrs);if(w<1||r<1)return toast('Each interval must be at least 1 second');S.walk=w;S.run=r;if(E.applyNow.checked){S.duration=S.phase==='walk'?w:r;S.left=S.duration;S.end=Date.now()+S.left*1000;S.last=Date.now()}phaseUI();renderRun();E.intervalModal.classList.remove('open');say('New intervals applied')}
function personPose(name,pose){const P={
push:[['70','107','115','112','166','121','88','144','146','150'],['70','128','115','130','166','132','90','151','148','152'],['70','107','115','112','166','121','88','144','146','150']],
squat:[['120','55','120','105','90','146','150','146'],['120','78','120','122','86','148','154','148'],['120','55','120','105','90','146','150','146']],
sit:[['78','72','112','118','166','145','92','147'],['112','55','122','112','166','145','93','147'],['78','72','112','118','166','145','92','147']],
lunge:[['120','50','120','102','78','146','174','146'],['120','72','120','116','76','146','174','146'],['120','50','120','102','78','146','174','146']],
plank:[['58','99','119','111','190','126','78','147','170','149'],['58','102','119','114','190','129','78','150','170','151'],['58','99','119','111','190','126','78','147','170','149']],
climber:[['58','93','119','109','184','123','79','147','153','147'],['58','93','119','109','184','123','79','147','105','147'],['58','93','119','109','184','123','79','147','176','147']],
burpee:[['120','48','120','101','91','145','149','145'],['74','112','120','126','179','136','92','151','151','151'],['120','38','120','93','87','137','153','137']],
jack:[['120','48','120','101','98','146','142','146'],['120','48','120','101','71','146','169','146'],['120','48','120','101','98','146','142','146']]
};return P[name][pose]}
function drawPerson(type,pose){const a=personPose(type,pose);if(['push','plank','climber'].includes(type)||type==='burpee'&&pose===1){const [hx,hy,sx,sy,fx,fy,ax,ay,lx,ly]=a;return `<g class="pose${['A','B','C'][pose]}"><ellipse class="mat" cx="125" cy="153" rx="104" ry="10"/><circle class="skin" cx="${hx}" cy="${hy}" r="13"/><path class="limb" d="M${Number(hx)+14} ${Number(hy)+3} L${sx} ${sy} L${fx} ${fy}"/><path class="limb" d="M${Number(sx)-18} ${Number(sy)-4} L${ax} ${ay} M${Number(sx)+26} ${Number(sy)+5} L${lx} ${ly}"/><path class="shirt" d="M${Number(hx)+13} ${Number(hy)-5} L${Number(sx)+8} ${Number(sy)-11} L${Number(sx)+17} ${Number(sy)+11} L${Number(hx)+16} ${Number(hy)+13} Z"/></g>`}const [hx,hy,sx,sy,lx,ly,rx,ry]=a;return `<g class="pose${['A','B','C'][pose]}"><ellipse class="mat" cx="120" cy="153" rx="92" ry="9"/><circle class="skin" cx="${hx}" cy="${hy}" r="13"/><path class="limb" d="M${hx} ${Number(hy)+14} L${sx} ${sy} M${sx} ${Number(sy)-28} L${Number(sx)-34} ${Number(sy)-6} M${sx} ${Number(sy)-28} L${Number(sx)+34} ${Number(sy)-6} M${sx} ${sy} L${lx} ${ly} M${sx} ${sy} L${rx} ${ry}"/><path class="shirt" d="M${Number(sx)-14} ${Number(sy)-45} Q${sx} ${Number(sy)-55} ${Number(sx)+14} ${Number(sy)-45} L${Number(sx)+13} ${Number(sy)-5} L${Number(sx)-13} ${Number(sy)-5} Z"/><path class="shorts" d="M${Number(sx)-14} ${Number(sy)-7} L${Number(sx)+14} ${Number(sy)-7} L${Number(sx)+20} ${Number(sy)+9} L${sx} ${Number(sy)+5} L${Number(sx)-20} ${Number(sy)+9} Z"/></g>`}
function demoSvg(type){return `<svg viewBox="0 0 240 180" aria-label="Animated ${type} form guide"><line class="floor" x1="20" y1="155" x2="220" y2="155"/>${drawPerson(type,0)}${drawPerson(type,1)}${drawPerson(type,2)}<path class="arrow" d="M210 55 Q225 90 210 125"/><path fill="#42d5a1" d="M204 119 L212 134 L219 119 Z"/></svg>`}
function renderExerciseGrid(){E.exerciseGrid.innerHTML=exercises.map((x,i)=>`<button class="exercise-card ${i===currentExercise?'selected':''}" data-i="${i}"><span>${x.icon}</span><strong>${x.name}</strong><small>${x.amount} ${x.unit}</small></button>`).join('');document.querySelectorAll('.exercise-card').forEach(b=>b.onclick=()=>{currentExercise=+b.dataset.i;exerciseAmount=exercises[currentExercise].amount;renderExerciseGrid();renderExercise()})}
function renderExercise(){const x=exercises[currentExercise];E.demo.innerHTML=`<span class="demo-badge">6-second form guide</span>${demoSvg(x.type)}<div class="demo-progress"><i></i></div>`;E.exerciseName.textContent=x.name;E.exerciseTarget.textContent=`${exerciseAmount} ${x.unit}`;E.exerciseTip.textContent=x.tip;E.exerciseAmount.textContent=exerciseAmount;E.exerciseUnit.textContent=x.unit}
function saveExercise(x,amount,duration){const h=history();h.unshift({type:x.name,date:new Date().toISOString(),duration,distance:0,cycles:amount,calories:Math.round((clamp(E.weight.value,30,250)||75)*duration/3600*6)});saveHistory(h)}
function startExercise(){const x=exercises[currentExercise];if(x.unit==='seconds'){let left=exerciseAmount;E.startExercise.textContent='Running…';say(`Start ${x.name}`);clearInterval(S.indoorTimer);S.indoorTimer=setInterval(()=>{left--;E.exerciseAmount.textContent=left;if(left<=0){clearInterval(S.indoorTimer);E.startExercise.textContent='Start exercise';E.exerciseAmount.textContent=exerciseAmount;say('Exercise complete');saveExercise(x,exerciseAmount,exerciseAmount)}},1000)}else{say(`Start ${x.name}. ${exerciseAmount} repetitions`);saveExercise(x,exerciseAmount,Math.round(exerciseAmount*3));toast('Exercise saved')}}
async function routeToStart(){if(!S.pos||!S.start)return toast('Start GPS tracking before routing');E.routeHome.textContent='Calculating…';try{const u=`https://routing.openstreetmap.de/routed-foot/route/v1/driving/${S.pos.longitude},${S.pos.latitude};${S.start.longitude},${S.start.latitude}?overview=full&steps=true&geometries=geojson`;const r=await fetch(u);const d=await r.json();if(!d.routes?.length)throw Error();const route=d.routes[0],coords=route.geometry.coordinates;const src=S.map?.getSource('route-home');if(src)src.setData({type:'Feature',geometry:{type:'LineString',coordinates:coords}});const bounds=coords.reduce((b,c)=>b.extend(c),new maplibregl.LngLatBounds(coords[0],coords[0]));S.map?.fitBounds(bounds,{padding:45});E.routeDistance.textContent=km(route.distance);E.routeDuration.textContent=`${Math.round(route.duration/60)} min walk`;const steps=route.legs.flatMap(l=>l.steps||[]);E.directionSteps.innerHTML=steps.map((x,i)=>`<div class="direction-step"><b>${i+1}</b><span>${instruction(x)}<br><small>${Math.round(x.distance)} m</small></span></div>`).join('');E.directions.classList.add('show')}catch{toast('Walking route could not be calculated')}finally{E.routeHome.textContent='↩ Route to start'}}
function instruction(x){const t=x.maneuver?.type||'continue',m=x.maneuver?.modifier||'';if(t==='depart')return`Start ${m}`;if(t==='arrive')return'You have reached your starting point';if(t==='turn')return`Turn ${m}`;if(t==='new name')return`Continue ${m}`;if(t==='roundabout')return'Enter the roundabout';return`${t.replaceAll('_',' ')} ${m}`.trim()}
function history(){return JSON.parse(localStorage.getItem('touraysHealthHistory')||localStorage.getItem('touraysHistory')||'[]')}function saveHistory(h){localStorage.setItem('touraysHealthHistory',JSON.stringify(h.slice(0,60)))}
function renderHealth(){const h=history(),now=new Date(),monday=new Date(now);monday.setDate(now.getDate()-((now.getDay()+6)%7));monday.setHours(0,0,0,0);const week=h.filter(x=>new Date(x.date)>=monday),mins=Math.round(week.reduce((a,x)=>a+(x.duration||0),0)/60),goal=Math.max(1,clamp(E.weeklyGoal.value,30,1000)||150),pct=Math.min(100,Math.round(mins/goal*100)),dist=h.reduce((a,x)=>a+(x.distance||0),0),cal=h.reduce((a,x)=>a+(x.calories||0),0),outdoor=h.filter(x=>(x.distance||0)>50),outTime=outdoor.reduce((a,x)=>a+(x.duration||0),0),outDist=outdoor.reduce((a,x)=>a+(x.distance||0),0);E.weeklyMinutes.textContent=`${mins} active min`;E.weeklyMessage.textContent=`${Math.max(0,goal-mins)} min remaining to your goal`;E.goalProgress.style.strokeDashoffset=201*(1-pct/100);E.goalPercent.textContent=`${pct}%`;E.healthCalories.textContent=`${cal} kcal`;E.healthDistance.textContent=km(dist);const w=(clamp(E.weight.value,30,250)||75),ht=(clamp(E.height.value,120,230)||0)/100,bmi=ht?w/(ht*ht):0;E.healthBmi.textContent=bmi?bmi.toFixed(1):'--';E.bmiLabel.textContent=bmi<18.5?'Below standard range':bmi<25?'Standard range':bmi<30?'Above standard range':'High range';E.healthPace.textContent=outDist>50?`${Math.floor((outTime/(outDist/1000))/60)}:${String(Math.round((outTime/(outDist/1000))%60)).padStart(2,'0')}/km`:'--';E.historyList.innerHTML=h.length?h.slice(0,20).map(x=>`<article class="history-item"><div class="history-head"><strong>${x.type||'Workout'}</strong><small>${new Date(x.date).toLocaleDateString()} · ${new Date(x.date).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></div><div class="history-values"><div><span>TIME</span><strong>${fmt(x.duration||0)}</strong></div><div><span>DISTANCE</span><strong>${km(x.distance||0)}</strong></div><div><span>CALORIES</span><strong>${x.calories||0}</strong></div></div></article>`).join(''):'<div class="empty">No workouts saved yet.</div>'}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>show(b.dataset.screen));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));document.querySelectorAll('.preset').forEach(b=>b.onclick=()=>{setTime(+b.dataset.w,E.wm,E.ws);setTime(+b.dataset.r,E.rm,E.rs);document.querySelectorAll('.preset').forEach(x=>x.classList.toggle('selected',x===b))});
E.startRun.onclick=startRun;E.pauseRun.onclick=pauseRun;E.stopRun.onclick=stopRun;E.changeIntervals.onclick=openIntervals;E.closeIntervals.onclick=()=>E.intervalModal.classList.remove('open');E.applyIntervals.onclick=applyIntervals;E.settingsBtn.onclick=()=>E.settingsModal.classList.add('open');E.closeSettings.onclick=()=>E.settingsModal.classList.remove('open');E.soundBtn.onclick=()=>{S.sound=!S.sound;E.soundBtn.textContent=S.sound?'🔊':'🔇'};E.intervalModal.onclick=x=>{if(x.target===E.intervalModal)E.intervalModal.classList.remove('open')};E.settingsModal.onclick=x=>{if(x.target===E.settingsModal)E.settingsModal.classList.remove('open')};
E.lessExercise.onclick=()=>{exerciseAmount=Math.max(1,exerciseAmount-(exercises[currentExercise].unit==='seconds'?5:1));renderExercise()};E.moreExercise.onclick=()=>{exerciseAmount+=exercises[currentExercise].unit==='seconds'?5:1;renderExercise()};E.startExercise.onclick=startExercise;E.recenterMap.onclick=()=>{if(S.map&&S.pos)S.map.flyTo({center:[S.pos.longitude,S.pos.latitude],zoom:17,pitch:45});else toast('Waiting for GPS')};E.routeHome.onclick=routeToStart;[E.weight,E.height,E.weeklyGoal].forEach(x=>x.onchange=renderHealth);E.gpsToggle.onchange=()=>{S.gps=E.gpsToggle.checked;S.gps?startGps():stopGps()};
renderExerciseGrid();renderExercise();startGps();renderHealth();
